classname: pipelines.metocean.pipeline.Metocean

triggers:
  - .*buoy\.z05.*\.zip

retriever:
  path: pipelines/metocean/config/retriever.yaml

dataset:
  path: pipelines/metocean/config/dataset.yaml
  overrides:
    /attrs/location_id: humboldt
    /attrs/location_meaning: "Humboldt, CA"
    /attrs/z_id: z05

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
