classname: pipelines.waves.pipeline.Waves

triggers:
  - .*buoy.z05.*waves\.csv

retriever:
  path: pipelines/waves/config/retriever.yaml

dataset:
  path: pipelines/waves/config/dataset.yaml
  overrides:
    /attrs/location_id: humboldt
    /attrs/location_meaning: "Humboldt, CA"
    /attrs/z_id: z05

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
