# DEVELOPER: Add attrs and coords/variables to specify the output data structure

attrs:
  title: {{ cookiecutter.ingest_name }}
  description: {{ cookiecutter.ingest_description }}
  location_id: {{ cookiecutter.location_id }}
  dataset_name: {{ cookiecutter.module }}
  z_id: z01
  data_level: {% if cookiecutter.use_custom_qc == "no" %}a0{% else %}b0{% endif %}
  # qualifier: 
  # temporal: 
  # institution: 

coords:
  time:
    dims: [time]
    dtype: datetime64[ns]
    attrs:
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  example_var:
    dims: [time]
    dtype: float
    attrs:
      long_name:  Example Variable
      units: km
