# Conda environment for developing tsdat pipelines

name: tsdat-pipelines
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - act-atmos
  - pip:
      - tsdat>=0.5.5,<0.6.0
      - cmocean
      - cookiecutter==2.1.1
      - pytest
      - coverage
      - mypy
      - black
      - isort
      - notebook
      - metpy
