classname: pipelines.lidar.pipeline.Lidar

triggers:
  - .*lidar.z06.*\.sta.7z

retriever:
  path: pipelines/lidar/config/retriever.yaml

dataset:
  path: pipelines/lidar/config/dataset.yaml
  overrides:
    /attrs/location_id: morro
    /attrs/location_meaning: Morro Bay, CA
    /attrs/z_id: z06

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
