classname: pipelines.lidar.pipeline.Lidar

triggers:
  - .*lidar.z07.*\.sta.7z

retriever:
  path: pipelines/lidar/config/retriever.yaml

dataset:
  path: pipelines/lidar/config/dataset.yaml
  overrides:
    /attrs/location_id: oahu
    /attrs/location_meaning: "Oahu, HI"
    /attrs/dataset_name: buoy_z07

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
