classname: pipelines.lidar.pipeline.Lidar

triggers:
  - .*lidar.z05.*\.sta.7z

retriever:
  path: pipelines/lidar/config/retriever.yaml

dataset:
  path: pipelines/lidar/config/dataset.yaml
  overrides:
    /attrs/location_id: humboldt
    /attrs/location_meaning: Humboldt, CA
    /attrs/z_id: z05

quality:
  path: shared/quality.yaml

storage:
  path: shared/storage.yaml
